sudo: required
language: node_js
node_js:
- '13'
before_script:
- npm install
script:
- npm run test
deploy:
  provider: heroku
  app: richi-sh
  api_key:
    secure: B60iUP9MJlaQO/V+9KRlmtmRT4ERWgsEYh+fnN7j/ceIEiitsCQ9yJhnWqFc7/KnPKwNXTsb4ZdttWOAT2O1p8kbhimWe6lMmgbAHf5WIg6uX/uF+HWt4HMrCkJVsSqXiEDlKluDIebQhZDc5bavOZv3djEtMDeinlYUXdVgfpe04zWqb1jwI2hS18KNIjnm63EKpmHrekOaWSmhU4OUcVY6tb3vP4S2yfReJxv8F9qdFWr8ZwV0iZ7nS/yFzkXEyX3ZahcolmWwfb71i356uobagr6fq4YWWSauwund/BqqpCrHpbLh5M3pOzhZu7z25ebe7TmxCdIVUj5t0pe81Iq1TMWn/ttQUqnX37bWWz59L+YKWte9JCX4EMAMxiep2GoNZvoxBZxPloIkN3CHOPbid2/HpwFW31uJfXqXn4HVyOdjtvPQHVDYaqe1047AHc+ziFmXYxy8xjARnbyDWFAzheiHIlV+Bl3QysD/VoutyStsLtSO2M/FcRwOwENQBdJQ0o7adiE4ztecJKvUTVx6ljeheFKPrpFjYxoFSnZaMpkR/+4w8UbdDYzlVurVXtz58WO0Nh4VXqKTzzmwqFydX2+FeQCwA0XxCZFY+3+o2clTy7Zl71hMyl20goI35Gc4vNR+EySV+mqkop64YvSBAS3khWFLqczmoV9bwng=
  on:
    repo: lutaev/richi
