sudo: required
language: node_js
node_js:
- '8'
before_script:
- npm install
script:
- npm run test
deploy:
  provider: heroku
  app: richi-sh
  api_key:
    secure: 775cdc17-3e24-41f4-a025-3fe418661dc8
