sudo: required
language: node_js
node_js:
- '13'
env:
  global:
  - PG_SQL_USER=hsxyxlxq
  - PG_SQL_HOST=balarama.db.elephantsql.com
  - PG_SQL_DB=hsxyxlxq
  - PG_SQL_TEST_USER=gskibphv
  - PG_SQL_TEST_HOST=drona.db.elephantsql.com
  - PG_SQL_TEST_DB=gskibphv
  - secure: GBKHYfo8ZR9rV6VrNOQjplHlOzft+EGEL91e+3/B/wFe3Z5gAqKIrfn9vJfxqi67vPJfJq4S5FsRJQMe1cyZiwqqOaM4AajQe+QKuNEGr+kDIdFKUNRC4GdboxMwIEAxuD6wzalDbBIDPcRS/Y2AZeJpAeTU3Piji+AxV2sb7LmlU2zuh6HSHzBJJbxkXo/uSf41S7rzih9hvM9jonr/KkVJRTe+pNYC7WhPMETu/mKOMy+0J5AxnWcdHtr5n9SwwDs6kQmUKEpV3zIhRdSXUTZQ4sRUncBmCZblAohJ4fjTH7tK5wi43kGn20j+xoKKB5R1ptq0w/mVymU+NsqyS3KZ+zTaF9iDKqRRf68eX7wRPKdDxHTOfxEafxgUsuSOw4pPxe0IdsQXFUNkYlGqACx9UAR6UtSxfOjoDQ+wWrpFSyDz7YWLrbhQvSIcyLp7lXKKOrZ0T1xrIJL0yb1e3W6I6G2sPFUoeoJjnT1qZXh7+Tmz42BKIrFohD0nzRxu1MsrFPh8xa8P+cVhoblNghbgdK7A3BhWtJLYQtDcAxQj0FmeLYleB5V8rQt/zBb8GOH2wQ5IotIqO5Qb2iNCAuu4MtqgD9U7NZgLARxkqf5IyTwEYG4/ZJ+q8/+xxMRT/sx+MV9NmGRkjb9AzI2I1bipkfDY/ywgNFwa4JgobMk=
  - secure: CWKJeAWNn8C2ziy19a50qGLnZkwfp0u5nV+jpQ9vKseEH4oUjcteyuA4amYHY8vCzmNxdcDErezlaBwJ0yiPx1xbCMipsZLAy3oQcKlOPKdqm3DqQAarBq9PYf2LXjisFYsmDJz248rTXI4j9Waddy+Th9PAMDp3srKreR+9vEhi+BE3Mxy03+NbfI3jhc9OuRTofLHv6Vzm+4tYxgE/ODsGpCu31rTBrFzOGdhXB4eLwhOi1qV7IWWD6L4lmJx9DPsLgyt3cZKvV1mbNNz2I/JTHju4IccUx0Ro+b+ZDFarVdXEzuqI1dehHuVry/XWRa7OGpN/nSSK52IWd6cRG6GgTjWE55AACveexTM4Ob5qn/OgVRJBPllnEsEVlUlKzxZe/4RlKY7fNfbpAp+qBW5qFvFJJoopXkX5uiSeziXOaQETKCGJcoyBOlDTLLN5KYAEI+FDKIom/ynajnsb9ACxkQioBuOQA98I3YXGAOAYkCySh+EuAmFPMNRKgoAVGrq5Dz6DznPM2JDQDWppf6hZQSV1Sv2B64l8h6BahD4wb5MLuE9sBYXmKW4iJwN+sfn9I41afIpoQSRC0j+7NeMyY4AovUgEd7iK0xhuxT3sMV6oNQnVUm3rUhRB91BokqIUPr/ybUHcFmLAeA9pddNTo3GO+cfdaf+JEZ92nqo=
before_script:
- npm install
script:
- npm run migrate:test
- npm run test
deploy:
  provider: heroku
  app: richi-sh
  api_key:
    secure: B60iUP9MJlaQO/V+9KRlmtmRT4ERWgsEYh+fnN7j/ceIEiitsCQ9yJhnWqFc7/KnPKwNXTsb4ZdttWOAT2O1p8kbhimWe6lMmgbAHf5WIg6uX/uF+HWt4HMrCkJVsSqXiEDlKluDIebQhZDc5bavOZv3djEtMDeinlYUXdVgfpe04zWqb1jwI2hS18KNIjnm63EKpmHrekOaWSmhU4OUcVY6tb3vP4S2yfReJxv8F9qdFWr8ZwV0iZ7nS/yFzkXEyX3ZahcolmWwfb71i356uobagr6fq4YWWSauwund/BqqpCrHpbLh5M3pOzhZu7z25ebe7TmxCdIVUj5t0pe81Iq1TMWn/ttQUqnX37bWWz59L+YKWte9JCX4EMAMxiep2GoNZvoxBZxPloIkN3CHOPbid2/HpwFW31uJfXqXn4HVyOdjtvPQHVDYaqe1047AHc+ziFmXYxy8xjARnbyDWFAzheiHIlV+Bl3QysD/VoutyStsLtSO2M/FcRwOwENQBdJQ0o7adiE4ztecJKvUTVx6ljeheFKPrpFjYxoFSnZaMpkR/+4w8UbdDYzlVurVXtz58WO0Nh4VXqKTzzmwqFydX2+FeQCwA0XxCZFY+3+o2clTy7Zl71hMyl20goI35Gc4vNR+EySV+mqkop64YvSBAS3khWFLqczmoV9bwng=
  on:
    repo: lutaev/richi
